use_frameworks!

platform :ios, '8.0'

target 'KWHttpManager_Example' do
  pod 'KWHttpManager', :path => '../'

  target 'KWHttpManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
